name: Workflow with Environment Variables
on: workflow_dispatch
env:
  HOSTNAME: Workflow-level-host
jobs:
  job-1:
    env:
      API_KEY: 1234
      HOSTNAME: Job-level-host
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repositary
        uses: actions/checkout@v4
      - name: Print API key
        run: echo "Env value - ${{env.API_KEY}}"
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "14.17.6"
      - name: Install Dependencies for Project
        run: npm i
      - name: Success
        run: echo "Successfully started! $HOSTNAME"
      - name: Accessing Secrets
        run: echo "Username Secret Value - ${{secrets.USERNAME}}"
      - name: Print Env Specific Values
        run: echo "Username - $USERNAME || Password - $PASSWORD"
  job-2:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Print Jobname
        run: echo "Echoing from Job 2"
      - name: Success
        run: echo "Successfully started! $HOSTNAME"
      - name: Print Env Specific Values
        run: echo "Username - $USERNAME || Password - $PASSWORD"
