name: Workflow with Environment Variables
on: workflow_dispatch
env:
  HOSTNAME: Workflow-level-host
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repositary
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "14.17.6"
      - name: Install Dependencies for Project
        run: npm i
      - name: Run Project
        run: npm start
      - name: Success
        run: echo "Successfully started!"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Jobname
        run: echo "Echoing from Job 2"
