name: Workflow with Job Outputs
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step4.outputs.val}}
    steps:
      - name: Fetch Repositary
        uses: actions/checkout@v4

      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "14.17.6"
      - name: Install Dependencies for Project
        run: npm i
      - name: Set Value for Job Output
        id: step4
        run: echo "val=hello-world" >> "$GITHUB_OUTPUT"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: Print Jobname
        run: echo "Echoing from Job 2"
      - name: Get Job Output Value from Job-1
        run: echo "${{needs.job-1.outputs.output1}}"
