name: Workflow with Event Activity Types
on:
  pull_request:
    types:
      - closed
      - opened
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "PR Closed"
