name: Workflow with Events
on:
  push:
    branches:
      - main
      - feature/* #feature/hello | feature/hello-world
      - feature/** # feature/hello/world
    paths:
      - "temp.md"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "step one"
